In [1]:
import numpy as np
np.set_printoptions(linewidth=300)

In [2]:
A = np.array([
  [0, 1, 1, 0, 0, 1, 0, 0, 1, 1],
  [1, 0, 1, 0, 0, 0, 0, 0, 0, 0],
  [1, 1, 0, 0, 0, 0, 0, 0, 0, 0],
  [0, 0, 0, 0, 1, 1, 0, 0, 0, 0],
  [0, 0, 0, 1, 0, 1, 0, 0, 0, 0],
  [1, 0, 0, 1, 1, 0, 1, 1, 0, 0],
  [0, 0, 0, 0, 0, 1, 0, 1, 0, 0],
  [0, 0, 0, 0, 0, 1, 1, 0, 0, 0],
  [1, 0, 0, 0, 0, 0, 0, 0, 0, 1],
  [1, 0, 0, 0, 0, 0, 0, 0, 1, 0]])

D = np.diag(A.sum(axis=1))
print(D)

[[5 0 0 0 0 0 0 0 0 0]
 [0 2 0 0 0 0 0 0 0 0]
 [0 0 2 0 0 0 0 0 0 0]
 [0 0 0 2 0 0 0 0 0 0]
 [0 0 0 0 2 0 0 0 0 0]
 [0 0 0 0 0 5 0 0 0 0]
 [0 0 0 0 0 0 2 0 0 0]
 [0 0 0 0 0 0 0 2 0 0]
 [0 0 0 0 0 0 0 0 2 0]
 [0 0 0 0 0 0 0 0 0 2]]


In [3]:
L = D-A
print(L)

[[ 5 -1 -1  0  0 -1  0  0 -1 -1]
 [-1  2 -1  0  0  0  0  0  0  0]
 [-1 -1  2  0  0  0  0  0  0  0]
 [ 0  0  0  2 -1 -1  0  0  0  0]
 [ 0  0  0 -1  2 -1  0  0  0  0]
 [-1  0  0 -1 -1  5 -1 -1  0  0]
 [ 0  0  0  0  0 -1  2 -1  0  0]
 [ 0  0  0  0  0 -1 -1  2  0  0]
 [-1  0  0  0  0  0  0  0  2 -1]
 [-1  0  0  0  0  0  0  0 -1  2]]


In [4]:
# L = np.array([[ 2.94303553 ,-0.73575888 , 0.        , -0.73575888 ,-0.73575888 ,-0.73575888],
#  [-0.73575888 , 2.94303553, -0.73575888 , 0.         ,-0.73575888 ,-0.73575888],
#  [ 0.        , -0.73575888 , 2.94303553, -0.73575888 ,-0.73575888, -0.73575888],
#  [-0.73575888,  0.         ,-0.73575888 , 2.94303553 ,-0.73575888 ,-0.73575888],
#  [-0.73575888 ,-0.73575888 ,-0.73575888, -0.73575888 , 2.94303553 , 0.        ],
#  [-0.73575888, -0.73575888 ,-0.73575888 ,-0.73575888 , 0.         , 2.94303553]])

In [5]:
vals, vecs = np.linalg.eig(L)

In [6]:
sorted_valsindex = np.argsort(vals)

In [7]:
vecs = vecs[:,sorted_valsindex]
vals = vals[sorted_valsindex]

In [8]:
vals

array([-2.54963072e-16,  2.98437881e-01,  1.00000000e+00,  1.00000000e+00,  3.00000000e+00,  3.00000000e+00,  3.00000000e+00,  3.00000000e+00,  5.00000000e+00,  6.70156212e+00])

In [9]:
vecs

array([[ 3.16227766e-01,  2.34057253e-01,  1.79797189e-16, -3.31980002e-17, -1.83096341e-17, -2.30895137e-17,  2.60612071e-18, -6.67875472e-19, -6.32455532e-01,  6.67245983e-01],
       [ 3.16227766e-01,  3.33622992e-01, -4.99934074e-01,  9.66226208e-02, -4.23621856e-02,  7.05622358e-01,  4.28068208e-02,  1.52799761e-01,  1.58113883e-01, -1.17028626e-01],
       [ 3.16227766e-01,  3.33622992e-01, -4.99934074e-01,  9.66226208e-02,  4.23621856e-02, -7.05622358e-01, -4.28068208e-02, -1.52799761e-01,  1.58113883e-01, -1.17028626e-01],
       [ 3.16227766e-01, -3.33622992e-01,  8.11924196e-03, -4.90575243e-01,  7.04888157e-01,  4.57939795e-02, -5.03825979e-02, -1.07667557e-01,  1.58113883e-01,  1.17028626e-01],
       [ 3.16227766e-01, -3.33622992e-01,  8.11924196e-03, -4.90575243e-01, -7.04888157e-01, -4.57939795e-02,  5.03825979e-02,  1.07667557e-01,  1.58113883e-01,  1.17028626e-01],
       [ 3.16227766e-01, -2.34057253e-01, -6.71572298e-17, -6.20706936e-17, -1.57029593e-17,  3.16351730e

In [10]:
round_vals = np.round(vals, 4)
round_vals

array([-0.    ,  0.2984,  1.    ,  1.    ,  3.    ,  3.    ,  3.    ,  3.    ,  5.    ,  6.7016])

In [11]:
round_vecs = np.round(vecs, 4)
round_vecs

array([[ 0.3162,  0.2341,  0.    , -0.    , -0.    , -0.    ,  0.    , -0.    , -0.6325,  0.6672],
       [ 0.3162,  0.3336, -0.4999,  0.0966, -0.0424,  0.7056,  0.0428,  0.1528,  0.1581, -0.117 ],
       [ 0.3162,  0.3336, -0.4999,  0.0966,  0.0424, -0.7056, -0.0428, -0.1528,  0.1581, -0.117 ],
       [ 0.3162, -0.3336,  0.0081, -0.4906,  0.7049,  0.0458, -0.0504, -0.1077,  0.1581,  0.117 ],
       [ 0.3162, -0.3336,  0.0081, -0.4906, -0.7049, -0.0458,  0.0504,  0.1077,  0.1581,  0.117 ],
       [ 0.3162, -0.2341, -0.    , -0.    , -0.    ,  0.    ,  0.    ,  0.    , -0.6325, -0.6672],
       [ 0.3162, -0.3336, -0.0081,  0.4906,  0.0089,  0.    ,  0.6909, -0.1286,  0.1581,  0.117 ],
       [ 0.3162, -0.3336, -0.0081,  0.4906, -0.0089,  0.    , -0.6909,  0.1286,  0.1581,  0.117 ],
       [ 0.3162,  0.3336,  0.4999, -0.0966,  0.0355, -0.    , -0.135 , -0.6697,  0.1581, -0.117 ],
       [ 0.3162,  0.3336,  0.4999, -0.0966, -0.0355, -0.    ,  0.135 ,  0.6697,  0.1581, -0.117 ]])

In [12]:
fiedler_vector = round_vecs[:,1]
fiedler_vector

array([ 0.2341,  0.3336,  0.3336, -0.3336, -0.3336, -0.2341, -0.3336, -0.3336,  0.3336,  0.3336])

In [13]:
phi = np.argsort(fiedler_vector)
phi_inv = np.argsort(phi)

In [14]:
sorted_fiedler_vector = fiedler_vector[phi]

In [15]:
sorted_fiedler_vector

array([-0.3336, -0.3336, -0.3336, -0.3336, -0.2341,  0.2341,  0.3336,  0.3336,  0.3336,  0.3336])

In [16]:
first_diff = np.diff(fiedler_vector[phi])
first_diff

array([0.    , 0.    , 0.    , 0.0995, 0.4682, 0.0995, 0.    , 0.    , 0.    ])

In [17]:
k = 3

In [18]:
jump_index_tmp = np.argsort(-(first_diff))
jump_index_tmp

array([4, 3, 5, 0, 1, 2, 6, 7, 8], dtype=int64)

In [19]:
jump_index = jump_index_tmp[:k-1]
jump_index = jump_index[np.argsort(jump_index)]
jump_index = jump_index +1 
jump_index = np.insert(jump_index,0,0)
jump_index = np.append(jump_index,10)# stat 10 face count
jump_index

array([ 0,  4,  5, 10], dtype=int64)

In [20]:
c = np.zeros(k)
for i in range(k):
    ctmp = np.sum(sorted_fiedler_vector[jump_index[i]:jump_index[i+1]])
    c[i] = ctmp/(jump_index[i+1]-jump_index[i])
c

array([-0.3336, -0.2341,  0.3137])

In [21]:
u_snake_sorted = np.repeat(c,np.diff(jump_index))
u_snake_sorted

array([-0.3336, -0.3336, -0.3336, -0.3336, -0.2341,  0.3137,  0.3137,  0.3137,  0.3137,  0.3137])

In [22]:
u_snake = u_snake_sorted[phi_inv]
u_snake

array([ 0.3137,  0.3137,  0.3137, -0.3336, -0.3336, -0.2341, -0.3336, -0.3336,  0.3137,  0.3137])

In [23]:
#zur visualisierung
ctemp = np.array(range(k))
u_snake_sorted_tmp = np.repeat(ctemp,np.diff(jump_index))
u_snake_sorted_tmp[phi_inv]

array([2, 2, 2, 0, 0, 1, 0, 0, 2, 2])